import type { TersaModel } from '../providers';
import { providers } from '../providers';

export const speechModels: Record<string, TersaModel> = {
  'eleven_turbo_v2_5': {
    label: 'Turbo v2.5 (AI/ML API)',
    chef: providers.elevenlabs,
    providers: [providers.elevenlabs],
    priceIndicator: 'lowest',
    default: true,
    voices: [
      // Female voices
      'Rachel',
      'Drew',
      'Aria',
      'Domi',
      'Sarah',
      'Laura',
      'Emily',
      'Elli',
      'Charlotte',
      'Alice',
      'Matilda',
      'Jessica',
      'Grace',
      'Lily',
      'Serena',
      'Nicole',
      'Jessie',
      'Glinda',
      'Mimi',
      // Male voices
      'Antoni',
      'Clyde',
      'Paul',
      'Dave',
      'Roger',
      'Fin',
      'Thomas',
      'Charlie',
      'George',
      'Callum',
      'Patrick',
      'River',
      'Harry',
      'Liam',
      'Josh',
      'Arnold',
      'Joseph',
      'Will',
      'Jeremy',
      'Eric',
      'Michael',
      'Ethan',
      'Chris',
      'Brian',
      'Daniel',
      'Adam',
      'Bill',
      'Sam',
      'Giovanni',
    ],
  },
  'openai-tts-1': {
    label: 'OpenAI TTS 1',
    chef: providers.openai,
    providers: [providers.openai],
    priceIndicator: 'low',
    voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'],
  },
  'openai-tts-1-hd': {
    label: 'OpenAI TTS 1 HD',
    chef: providers.openai,
    providers: [providers.openai],
    priceIndicator: 'low',
    voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'],
  },
};

export type SpeechModel = keyof typeof speechModels;
