# Generated by Django 5.2.3 on 2025-06-15 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField(db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("browser_version", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "website_custom_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("referrer", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.customsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhoisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("raw_whois_data", models.TextField(blank=True)),
                ("organization", models.CharField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("network_name", models.CharField(blank=True, max_length=200)),
                ("network_range", models.CharField(blank=True, max_length=100)),
                ("asn", models.CharField(blank=True, max_length=50)),
                ("asn_description", models.CharField(blank=True, max_length=500)),
                ("lookup_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("lookup_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-lookup_date"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="website_who_ip_addr_32eaf2_idx"
                    ),
                    models.Index(
                        fields=["country_code", "-lookup_date"],
                        name="website_who_country_1f9050_idx",
                    ),
                    models.Index(
                        fields=["organization", "-lookup_date"],
                        name="website_who_organiz_e80f29_idx",
                    ),
                    models.Index(
                        fields=["lookup_successful", "-lookup_date"],
                        name="website_who_lookup__4a976e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPLookupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("lookup_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "lookup_source",
                    models.CharField(
                        choices=[
                            ("session_tracking", "Session Tracking"),
                            ("manual_lookup", "Manual Lookup"),
                            ("admin_dashboard", "Admin Dashboard"),
                            ("api_request", "API Request"),
                        ],
                        default="session_tracking",
                        max_length=50,
                    ),
                ),
                ("lookup_successful", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.customsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whois_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.whoisrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-lookup_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="customsession",
            index=models.Index(
                fields=["session_key"], name="website_cus_session_0f67e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customsession",
            index=models.Index(
                fields=["expire_date"], name="website_cus_expire__609149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customsession",
            index=models.Index(
                fields=["user", "-last_activity"], name="website_cus_user_id_ef1526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customsession",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="website_cus_ip_addr_011dac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customsession",
            index=models.Index(
                fields=["device_type", "-created_at"],
                name="website_cus_device__250b6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "-timestamp"], name="website_pag_session_61c15b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "-timestamp"], name="website_pag_user_id_3bf210_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["path", "-timestamp"], name="website_pag_path_97a103_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["-timestamp"], name="website_pag_timesta_3a6d2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="iplookuplog",
            index=models.Index(
                fields=["ip_address", "-lookup_timestamp"],
                name="website_ipl_ip_addr_6d9476_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="iplookuplog",
            index=models.Index(
                fields=["lookup_source", "-lookup_timestamp"],
                name="website_ipl_lookup__c32886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="iplookuplog",
            index=models.Index(
                fields=["lookup_successful", "-lookup_timestamp"],
                name="website_ipl_lookup__e47cae_idx",
            ),
        ),
    ]
