# Generated by Django 5.2.3 on 2025-06-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_customsession_pageview_whoisrecord_iplookuplog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
