# Generated by Django 5.2.3 on 2025-06-18 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_brand_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this tweet configuration", max_length=100
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Template for generating tweets. Use {topic}, {tone}, {keywords} as placeholders."
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list, help_text="List of topics to tweet about"
                    ),
                ),
                (
                    "tones",
                    models.JSONField(
                        default=list,
                        help_text="List of tones to use (e.g., professional, casual, humorous)",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="List of keywords to include"
                    ),
                ),
                (
                    "hashtags",
                    models.JSONField(default=list, help_text="List of hashtags to use"),
                ),
                (
                    "schedule",
                    models.JSONField(
                        default=dict,
                        help_text="Schedule configuration (e.g., {'frequency': 'daily', 'time': '09:00', 'days': ['Mon', 'Wed', 'Fri']})",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweet_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "prompt_used",
                    models.TextField(
                        help_text="The actual prompt used to generate this tweet"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "tweet_id",
                    models.CharField(
                        blank=True,
                        help_text="Twitter's tweet ID after posting",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to="website.tweetconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
