# Generated by Django 5.2.3 on 2025-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_tweetconfiguration_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="twitter_access_token",
            field=models.CharField(
                blank=True, help_text="Twitter Access Token", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_access_token_secret",
            field=models.CharField(
                blank=True,
                help_text="Twitter Access Token Secret",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_api_key",
            field=models.CharField(
                blank=True,
                help_text="Twitter API Key (Consumer Key)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_api_secret",
            field=models.CharField(
                blank=True,
                help_text="Twitter API Secret (Consumer Secret)",
                max_length=255,
                null=True,
            ),
        ),
    ]
