# Generated by Django 5.2.3 on 2025-07-04 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_blogpost_blogcomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_points", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_signups", models.IntegerField(default=0)),
                ("total_subscriptions", models.IntegerField(default=0)),
                (
                    "total_rewards_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Code",
                "verbose_name_plural": "Referral Codes",
                "ordering": ["-total_points", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "runner_up",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_seconds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "third_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_thirds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Leaderboard",
                "verbose_name_plural": "Referral Leaderboards",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="ReferralSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reward_given", models.BooleanField(default=False)),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="website.referralcode",
                    ),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_signup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Signup",
                "verbose_name_plural": "Referral Signups",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReferralSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("subscription_type", models.CharField(max_length=50)),
                (
                    "subscription_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reward_given", models.BooleanField(default=False)),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "reward_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="website.referralcode",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Subscription",
                "verbose_name_plural": "Referral Subscriptions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReferralBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("first_referral", "First Referral"),
                            ("bronze_referrer", "Bronze Referrer (5 signups)"),
                            ("silver_referrer", "Silver Referrer (25 signups)"),
                            ("gold_referrer", "Gold Referrer (100 signups)"),
                            ("platinum_referrer", "Platinum Referrer (500 signups)"),
                            ("click_master", "Click Master (1000 clicks)"),
                            ("subscription_ace", "Subscription Ace (50 subscriptions)"),
                            ("top_earner", "Top Earner (monthly)"),
                            ("leaderboard_king", "Leaderboard King (weekly #1)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Badge",
                "verbose_name_plural": "Referral Badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge_type")},
            },
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="website.referralcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Click",
                "verbose_name_plural": "Referral Clicks",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["referral_code", "-timestamp"],
                        name="website_ref_referra_d61576_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="website_ref_ip_addr_d4ae99_idx",
                    ),
                ],
            },
        ),
    ]
