# Generated by Django 5.2.3 on 2025-07-04 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_referralcode_referralleaderboard_referralsignup_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralclick",
            unique_together={("referral_code", "ip_address")},
        ),
    ]
