# Generated by Django 5.2.3 on 2025-07-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_add_unique_constraint_referral_clicks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="additional_images/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="additional_image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="additional_images/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="banner_images/"),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="post_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for regular posts",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reel_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for reels",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="story_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for story posts",
                max_digits=10,
                null=True,
            ),
        ),
    ]
