# Generated by Django 5.2.3 on 2025-07-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_user_additional_image1_user_additional_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
