# Generated by Django 5.2.3 on 2025-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_brand_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="last_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Date of last successful payment", null=True
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="stripe_subscription_status",
            field=models.CharField(
                blank=True,
                help_text="Current Stripe subscription status (active, canceled, past_due, etc.)",
                max_length=50,
                null=True,
            ),
        ),
    ]
