# Generated by Django 5.2.3 on 2025-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_add_stripe_subscription_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
