# Generated by Django 5.2.3 on 2025-07-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_make_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="impressions_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this profile has been viewed"
            ),
        ),
        migrations.CreateModel(
            name="ProfileImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True)),
                (
                    "profile_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_impressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.customsession",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Impression",
                "verbose_name_plural": "Profile Impressions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["profile_user", "-timestamp"],
                        name="website_pro_profile_8390c0_idx",
                    ),
                    models.Index(
                        fields=["viewer", "-timestamp"],
                        name="website_pro_viewer__9fdc56_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="website_pro_ip_addr_2aa054_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="website_pro_timesta_a166ef_idx"
                    ),
                ],
                "unique_together": {("profile_user", "ip_address", "timestamp")},
            },
        ),
    ]
