# Generated by Django 5.2.3 on 2025-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_task_taskapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="cashfree_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="cashfree_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="cashfree_payment_status",
            field=models.CharField(
                blank=True,
                help_text="Current Cashfree payment status (PAID, PENDING, FAILED, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="preferred_payment_method",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("cashfree", "Cashfree")],
                default="stripe",
                help_text="Preferred payment method for this brand",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["brand", "-created_at"], name="website_tas_brand_i_c90d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["category", "-created_at"],
                name="website_tas_categor_81554e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["genre", "-created_at"], name="website_tas_genre_4a9d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["incentive_type", "-created_at"],
                name="website_tas_incenti_900983_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="website_tas_is_acti_253fe0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskapplication",
            index=models.Index(
                fields=["task", "-applied_at"], name="website_tas_task_id_07ab85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskapplication",
            index=models.Index(
                fields=["creator", "-applied_at"], name="website_tas_creator_dec30a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskapplication",
            index=models.Index(
                fields=["status", "-applied_at"], name="website_tas_status_f36b29_idx"
            ),
        ),
    ]
