# Generated by Django 5.2.3 on 2025-07-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_add_referrer_to_referralclick"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this variable",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The encrypted value. This will be automatically encrypted/decrypted."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this variable is used for",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variable is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this variable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_variables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this variable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_variables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encrypted Variable",
                "verbose_name_plural": "Encrypted Variables",
                "ordering": ["key"],
            },
        ),
        migrations.AddIndex(
            model_name="encryptedvariable",
            index=models.Index(fields=["key"], name="website_enc_key_6ee73a_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptedvariable",
            index=models.Index(
                fields=["is_active", "key"], name="website_enc_is_acti_a6cd52_idx"
            ),
        ),
    ]
