# Generated by Django 5.2.3 on 2025-07-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_brand_cashfree_customer_id_brand_cashfree_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=20)),
                (
                    "routing_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bank_name", models.CharField(max_length=200)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual Verification"),
                            ("penny_drop", "Penny Drop"),
                            ("api", "API Verification"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cashfree_bene_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Bank Account",
                "verbose_name_plural": "User Bank Accounts",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payout_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("task_payment", "Task Payment"),
                            ("referral_commission", "Referral Commission"),
                            ("bonus", "Bonus"),
                            ("refund", "Refund"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("cashfree", "Cashfree"), ("stripe", "Stripe")],
                        default="cashfree",
                        max_length=20,
                    ),
                ),
                (
                    "provider_transfer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referral_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="website.referralsubscription",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="website.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payout",
                "verbose_name_plural": "Payouts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="website_pay_user_id_8293ea_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="website_pay_status_b1afe1_idx",
                    ),
                    models.Index(
                        fields=["payment_provider", "-created_at"],
                        name="website_pay_payment_499de3_idx",
                    ),
                ],
            },
        ),
    ]
