# Generated by Django 5.2.3 on 2025-07-13 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_userbankaccount_payout"),
        ("website", "0017_add_service_models"),
    ]

    operations = []
