# Generated by Django 5.2.3 on 2025-07-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_merge_20250713_1630"),
    ]

    operations = [
        # Add social auth profile fields to User model
        migrations.AddField(
            model_name="user",
            name="social_avatar_url",
            field=models.URLField(
                blank=True, null=True, help_text="Avatar URL from social media profile"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_display_name",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                help_text="Display name from social media profile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_verified",
            field=models.BooleanField(
                default=False,
                null=True,
                help_text="Whether the user's social account is verified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_follower_count",
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                help_text="Follower count from primary social account",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_following_count",
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                help_text="Following count from primary social account",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_social_sync",
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Last time social data was synchronized",
            ),
        ),
        # Create SocialAuthLog model for tracking auth events
        migrations.CreateModel(
            name="SocialAuthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        related_name="social_auth_logs",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("twitter_oauth2", "Twitter OAuth 2.0"),
                            ("google", "Google"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                        ],
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("login", "Login"),
                            ("connect", "Connect"),
                            ("disconnect", "Disconnect"),
                            ("sync", "Sync"),
                            ("refresh", "Refresh Token"),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(null=True, blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Social Auth Log",
                "verbose_name_plural": "Social Auth Logs",
                "ordering": ["-created_at"],
            },
        ),
        # Add additional fields to ServiceConnection model
        migrations.AddField(
            model_name="serviceconnection",
            name="scopes",
            field=models.JSONField(
                default=list, help_text="OAuth scopes granted for this connection"
            ),
        ),
        migrations.AddField(
            model_name="serviceconnection",
            name="profile_data",
            field=models.JSONField(
                default=dict, help_text="Cached profile data from the service"
            ),
        ),
        migrations.AddField(
            model_name="serviceconnection",
            name="last_error",
            field=models.TextField(
                blank=True, help_text="Last error message from this connection"
            ),
        ),
        migrations.AddField(
            model_name="serviceconnection",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive failed attempts"
            ),
        ),
        migrations.AddField(
            model_name="serviceconnection",
            name="last_retry_at",
            field=models.DateTimeField(
                null=True, blank=True, help_text="Last time a retry was attempted"
            ),
        ),
        # Create SocialAuthSettings model for app-wide social auth
        # configuration
        migrations.CreateModel(
            name="SocialAuthSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        choices=[
                            ("twitter_oauth2", "Twitter OAuth 2.0"),
                            ("google", "Google"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("client_id", models.CharField(max_length=200, blank=True)),
                ("client_secret", models.CharField(max_length=200, blank=True)),
                ("scopes", models.JSONField(default=list)),
                ("additional_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Auth Settings",
                "verbose_name_plural": "Social Auth Settings",
            },
        ),
    ]
