# Generated by Django 5.2.3 on 2025-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_add_service_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceconnection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="serviceprompt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servicestats",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
