# Generated by Django 5.2.3 on 2025-07-13 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0019_add_social_auth_enhancements"),
        ("website", "0019_alter_serviceconnection_id_alter_serviceprompt_id_and_more"),
    ]

    operations = []
