# Generated by Django 5.2.3 on 2025-07-13 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("website", "0020_merge_20250713_1712"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="payout",
            name="referral_subscription",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="task",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="user",
        ),
        migrations.RemoveField(
            model_name="socialauthlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="SocialAuthSettings",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="serviceconnection",
            name="last_error",
        ),
        migrations.RemoveField(
            model_name="serviceconnection",
            name="last_retry_at",
        ),
        migrations.RemoveField(
            model_name="serviceconnection",
            name="profile_data",
        ),
        migrations.RemoveField(
            model_name="serviceconnection",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="serviceconnection",
            name="scopes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_social_sync",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_avatar_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_display_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_follower_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_following_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_verified",
        ),
        migrations.AddField(
            model_name="brand",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this brand belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="twitter_access_token",
            field=models.CharField(
                blank=True,
                help_text="Twitter Access Token for this brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="twitter_access_token_secret",
            field=models.CharField(
                blank=True,
                help_text="Twitter Access Token Secret for this brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="twitter_api_key",
            field=models.CharField(
                blank=True,
                help_text="Twitter API Key (Consumer Key) for this brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="twitter_api_secret",
            field=models.CharField(
                blank=True,
                help_text="Twitter API Secret (Consumer Secret) for this brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="twitter_username",
            field=models.CharField(
                blank=True,
                help_text="Twitter username for this brand",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="organizations.organization",
            ),
        ),
        migrations.DeleteModel(
            name="Payout",
        ),
        migrations.DeleteModel(
            name="SocialAuthLog",
        ),
        migrations.DeleteModel(
            name="UserBankAccount",
        ),
        migrations.AlterUniqueTogether(
            name="organizationinvitation",
            unique_together={("organization", "email")},
        ),
    ]
