# Generated by Django 5.2.3 on 2025-07-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_organizationinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="twitter_bearer_token",
            field=models.CharField(
                blank=True,
                help_text="Twitter Bearer Token for this brand (required for API v2)",
                max_length=255,
                null=True,
            ),
        ),
    ]
