# Generated by Django 5.2.3 on 2025-07-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_add_twitter_bearer_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, help_text="Tweet content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for the tweet",
                        null=True,
                        upload_to="brand_tweets/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "tweet_id",
                    models.CharField(
                        blank=True,
                        help_text="Twitter's tweet ID after posting",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this tweet should be posted",
                        null=True,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="AI prompt used to generate content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_tweets",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
    ]
