# Generated by Django 5.2.3 on 2025-07-14 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_add_brand_tweet_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("openai_text", "OpenAI Text Generation"),
                            ("openai_image", "OpenAI Image Generation"),
                            ("runware_image", "Runware Image Generation"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("daily_limit", models.PositiveIntegerField(default=10)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this service limit"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Service Limit",
                "verbose_name_plural": "AI Service Limits",
                "ordering": ["service"],
            },
        ),
        migrations.CreateModel(
            name="AIServiceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("openai_text", "OpenAI Text Generation"),
                            ("openai_image", "OpenAI Image Generation"),
                            ("runware_image", "Runware Image Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("usage_date", models.DateField(auto_now_add=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_service_usage",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date", "brand", "service"],
                "indexes": [
                    models.Index(
                        fields=["brand", "service", "usage_date"],
                        name="website_ais_brand_i_7a97a8_idx",
                    ),
                    models.Index(
                        fields=["usage_date"], name="website_ais_usage_d_a878a0_idx"
                    ),
                ],
                "unique_together": {("brand", "service", "usage_date")},
            },
        ),
        migrations.CreateModel(
            name="WebLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("minute_task", "Minute Task"),
                            ("deployment", "Deployment"),
                            ("system_event", "System Event"),
                            ("user_action", "User Action"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(help_text="Name of the activity", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Structured data about the activity"
                    ),
                ),
                (
                    "items_processed",
                    models.IntegerField(
                        default=0, help_text="Number of items processed"
                    ),
                ),
                (
                    "items_succeeded",
                    models.IntegerField(
                        default=0, help_text="Number of items that succeeded"
                    ),
                ),
                (
                    "items_failed",
                    models.IntegerField(
                        default=0, help_text="Number of items that failed"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, help_text="Full error traceback"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Log",
                "verbose_name_plural": "Web Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["activity_type", "-started_at"],
                        name="website_web_activit_16f9e5_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="website_web_status_f6b9db_idx",
                    ),
                    models.Index(
                        fields=["activity_name", "-started_at"],
                        name="website_web_activit_157bba_idx",
                    ),
                    models.Index(
                        fields=["-started_at"], name="website_web_started_ac77ed_idx"
                    ),
                ],
            },
        ),
    ]
