# Generated by Django 5.2.3 on 2025-07-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_add_tweet_url_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="instagram_access_token",
            field=models.CharField(
                blank=True,
                help_text="Instagram Access Token for this brand",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_app_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram App ID for this brand",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_app_secret",
            field=models.CharField(
                blank=True,
                help_text="Instagram App Secret for this brand",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_user_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram User ID for this brand",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_username",
            field=models.CharField(
                blank=True,
                help_text="Instagram username for this brand",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BrandInstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Instagram post caption"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for the Instagram post",
                        null=True,
                        upload_to="brand_instagram_posts/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "instagram_id",
                    models.CharField(
                        blank=True,
                        help_text="Instagram's post ID after posting",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to the post on Instagram",
                        null=True,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this post should be posted",
                        null=True,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="AI prompt used to generate content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_instagram_posts",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
    ]
