# Generated by Django 5.2.3 on 2025-07-19 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0026_brand_instagram_access_token_brand_instagram_app_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this asset", max_length=200
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                            ("logo", "Logo"),
                            ("graphic", "Graphic"),
                            ("template", "Template"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The asset file (image, video, etc.)",
                        upload_to="brand_assets/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for video assets or custom thumbnails",
                        null=True,
                        upload_to="brand_assets/thumbnails/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description or usage notes"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags for organizing assets (e.g., ['product', 'summer', 'promo'])",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image/video width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image/video height in pixels", null=True
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this asset is available for use",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this asset has been used in posts",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("brand", "name")},
            },
        ),
    ]
