# Generated by Django 5.2.3 on 2025-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_add_brand_asset_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinstagrampost",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Custom brand assets to include with this Instagram post",
                related_name="instagram_posts",
                to="website.brandasset",
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Custom brand assets to include with this tweet",
                related_name="tweets",
                to="website.brandasset",
            ),
        ),
    ]
