# Generated by Django 5.2.3 on 2025-07-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0028_add_assets_to_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="brand1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="brand2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="brand3",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="brand4",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="brand5",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True, help_text="Creator description/bio", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_url",
            field=models.URLField(blank=True, help_text="Instagram profile URL"),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, help_text="Creator display name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo1",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo4",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo5",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo6",
            field=models.ImageField(blank=True, null=True, upload_to="creator_photos/"),
        ),
    ]
