# Generated by Django 5.2.3 on 2025-07-20 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_add_twitter_fields_to_user"),
        ("website", "0029_add_creator_fields"),
    ]

    operations = []
