# Generated by Django 5.2.3 on 2025-07-20 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0030_merge_20250720_1256"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsPageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=500)),
                ("path", models.CharField(max_length=500)),
                ("query_params", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("scroll_depth_percentage", models.IntegerField(default=0)),
                ("clicks_count", models.IntegerField(default=0)),
                ("form_interactions", models.IntegerField(default=0)),
                ("viewport_width", models.IntegerField(null=True)),
                ("viewport_height", models.IntegerField(null=True)),
                ("screen_width", models.IntegerField(null=True)),
                ("screen_height", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "analytics_pageviews",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website_url", models.URLField()),
                ("tracking_code", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("record_mouse_movements", models.BooleanField(default=True)),
                ("record_clicks", models.BooleanField(default=True)),
                ("record_form_inputs", models.BooleanField(default=True)),
                ("record_scrolls", models.BooleanField(default=True)),
                ("sample_rate", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_projects",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_projects",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsFunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("steps", models.JSONField()),
                ("total_entries", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funnels",
                        to="website.analyticsproject",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_funnels",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("conversion_drop", "Conversion Rate Drop"),
                            ("traffic_spike", "Traffic Spike"),
                            ("error_increase", "Error Rate Increase"),
                            ("bounce_increase", "Bounce Rate Increase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="website.analyticsproject",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_alerts",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mouse_movements", models.TextField()),
                ("dom_mutations", models.TextField(blank=True)),
                ("console_logs", models.TextField(blank=True)),
                ("network_requests", models.TextField(blank=True)),
                ("recording_duration", models.IntegerField(default=0)),
                ("data_size_bytes", models.IntegerField(default=0)),
                ("compression_type", models.CharField(default="gzip", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pageview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="website.analyticspageview",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_recordings",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("referrer", models.URLField(blank=True)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("browser_version", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("page_views", models.IntegerField(default=0)),
                ("is_bounce", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="website.analyticsproject",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_sessions",
            },
        ),
        migrations.AddField(
            model_name="analyticspageview",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pageviews",
                to="website.analyticssession",
            ),
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("form_submit", "Form Submit"),
                            ("form_focus", "Form Focus"),
                            ("scroll", "Scroll"),
                            ("resize", "Window Resize"),
                            ("error", "JavaScript Error"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("element_tag", models.CharField(blank=True, max_length=50)),
                ("element_classes", models.TextField(blank=True)),
                ("element_id", models.CharField(blank=True, max_length=200)),
                ("element_text", models.TextField(blank=True)),
                ("x_coordinate", models.IntegerField(null=True)),
                ("y_coordinate", models.IntegerField(null=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "pageview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="website.analyticspageview",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "indexes": [
                    models.Index(
                        fields=["pageview", "timestamp"],
                        name="analytics_e_pagevie_e553ba_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="analytics_e_event_t_5b2eb4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsHeatmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url_pattern", models.CharField(max_length=500)),
                ("viewport_width", models.IntegerField()),
                ("viewport_height", models.IntegerField()),
                ("click_data", models.TextField()),
                ("scroll_data", models.TextField()),
                ("attention_data", models.TextField()),
                ("sample_size", models.IntegerField(default=0)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmaps",
                        to="website.analyticsproject",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_heatmaps",
                "unique_together": {
                    (
                        "project",
                        "url_pattern",
                        "viewport_width",
                        "viewport_height",
                        "date_from",
                    )
                },
            },
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["project", "-started_at"], name="analytics_s_project_ec3e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["session_id"], name="analytics_s_session_a33eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["-started_at"], name="analytics_s_started_ddde48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticspageview",
            index=models.Index(
                fields=["session", "-started_at"], name="analytics_p_session_1b3a60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticspageview",
            index=models.Index(fields=["url"], name="analytics_p_url_a6d1fd_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticspageview",
            index=models.Index(
                fields=["-started_at"], name="analytics_p_started_6dd6b6_idx"
            ),
        ),
    ]
