# Generated by Django 5.2.3 on 2025-07-20 19:40

from django.db import migrations, models


def safe_remove_index(apps, schema_editor):
    """Safely remove index if it exists"""
    if schema_editor.connection.vendor == "sqlite":
        # For SQLite, check if index exists before removing
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='website_pag_session_61c15b_idx'
            """
            )
            if cursor.fetchone():
                # Index exists, safe to remove
                cursor.execute("DROP INDEX IF EXISTS website_pag_session_61c15b_idx")
    else:
        # For other databases, use standard migration
        PageView = apps.get_model("website", "PageView")
        from django.db import models

        index = models.Index(fields=["session"], name="website_pag_session_61c15b_idx")
        try:
            schema_editor.remove_index(PageView, index)
        except Exception:
            # Index doesn't exist, skip
            pass


def reverse_safe_remove_index(apps, schema_editor):
    """Reverse operation - recreate index if needed"""
    pass  # We don't need to recreate the index


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0032_safe_remove_session_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="iplookuplog",
            name="session",
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="session",
        ),
        migrations.RemoveField(
            model_name="profileimpression",
            name="session",
        ),
        migrations.RunPython(safe_remove_index, reverse_safe_remove_index),
        migrations.AddField(
            model_name="brandtweet",
            name="clicks",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of clicks/engagement for this tweet"
            ),
        ),
        migrations.DeleteModel(
            name="CustomSession",
        ),
    ]
