# Generated by Django 5.2.3 on 2025-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0033_add_clicks_to_brandtweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slack_channel",
            field=models.CharField(
                blank=True,
                help_text="Slack channel for notifications (optional)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="slack_notifications_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Slack notifications for this brand"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="slack_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Slack webhook URL for tweet queue notifications",
                null=True,
            ),
        ),
    ]
