# Generated by Django 5.2.3 on 2025-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0034_add_slack_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticspageview",
            name="dom_content_loaded_ms",
            field=models.IntegerField(
                blank=True, help_text="Time until DOM content loaded in ms", null=True
            ),
        ),
        migrations.AddField(
            model_name="analyticspageview",
            name="first_input_delay_ms",
            field=models.FloatField(
                blank=True, help_text="First input delay in ms", null=True
            ),
        ),
        migrations.AddField(
            model_name="analyticspageview",
            name="first_paint_ms",
            field=models.IntegerField(
                blank=True, help_text="Time to first paint in ms", null=True
            ),
        ),
        migrations.AddField(
            model_name="analyticspageview",
            name="largest_contentful_paint_ms",
            field=models.IntegerField(
                blank=True,
                help_text="Time to largest contentful paint in ms",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticspageview",
            name="load_time_ms",
            field=models.IntegerField(
                blank=True, help_text="Total page load time in ms", null=True
            ),
        ),
    ]
