# Generated by Django 5.2.3 on 2025-07-25 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("website", "0035_add_page_load_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                            ("note", "Note"),
                            ("proposal", "Proposal Sent"),
                            ("demo", "Demo/Presentation"),
                            ("follow_up", "Follow Up"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Result or notes from the activity"
                    ),
                ),
                (
                    "next_action",
                    models.CharField(
                        blank=True, help_text="Planned next step", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "CRM Activities",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("customer", "Customer"),
                            ("partner", "Partner"),
                            ("vendor", "Vendor"),
                            ("other", "Other"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("email_marketing", "Email Marketing"),
                            ("cold_outreach", "Cold Outreach"),
                            ("event", "Event"),
                            ("partner", "Partner"),
                            ("advertising", "Advertising"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_contact_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=10, help_text="Probability of closing (0-100%)"
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lost_reason",
                    models.TextField(blank=True, help_text="Reason if deal was lost"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, help_text="Only visible to creator"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CRMPipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Default probability for this stage (0-100%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed_won", models.BooleanField(default=False)),
                ("is_closed_lost", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pipeline", "order"],
            },
        ),
        migrations.CreateModel(
            name="CRMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="crmactivity",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmactivity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmactivity",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_activities",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="crmcontact",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcontact",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcontact",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_contacts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="crmactivity",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="website.crmcontact",
            ),
        ),
        migrations.AddField(
            model_name="crmdeal",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmdeal",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="website.crmcontact",
            ),
        ),
        migrations.AddField(
            model_name="crmdeal",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmdeal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_deals",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="crmactivity",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="website.crmdeal",
            ),
        ),
        migrations.AddField(
            model_name="crmnote",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_notes",
                to="website.crmcontact",
            ),
        ),
        migrations.AddField(
            model_name="crmnote",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmnote",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_notes",
                to="website.crmdeal",
            ),
        ),
        migrations.AddField(
            model_name="crmnote",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_notes",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="crmpipeline",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_pipelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmpipeline",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_pipelines",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="crmpipelinestage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="website.crmpipeline",
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_crm_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="website.crmcontact",
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_crm_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="website.crmdeal",
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_tasks",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcontact",
            index=models.Index(
                fields=["organization", "contact_type"],
                name="website_crm_organiz_8aafb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcontact",
            index=models.Index(
                fields=["assigned_to", "-created_at"],
                name="website_crm_assigne_691b86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcontact",
            index=models.Index(fields=["email"], name="website_crm_email_ecc739_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="crmcontact",
            unique_together={("organization", "email")},
        ),
        migrations.AddIndex(
            model_name="crmdeal",
            index=models.Index(
                fields=["organization", "stage"], name="website_crm_organiz_a0db12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmdeal",
            index=models.Index(
                fields=["assigned_to", "-created_at"],
                name="website_crm_assigne_1dcca9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmdeal",
            index=models.Index(
                fields=["expected_close_date"], name="website_crm_expecte_00c1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmactivity",
            index=models.Index(
                fields=["organization", "status"], name="website_crm_organiz_3e48ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmactivity",
            index=models.Index(
                fields=["assigned_to", "scheduled_at"],
                name="website_crm_assigne_076de8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmactivity",
            index=models.Index(
                fields=["contact", "-created_at"], name="website_crm_contact_4afd9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmnote",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="website_crm_organiz_3d5ad1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmnote",
            index=models.Index(
                fields=["contact", "-created_at"], name="website_crm_contact_5be2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmnote",
            index=models.Index(
                fields=["deal", "-created_at"], name="website_crm_deal_id_8cff81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="crmpipeline",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="crmpipelinestage",
            unique_together={("pipeline", "name")},
        ),
        migrations.AddIndex(
            model_name="crmtask",
            index=models.Index(
                fields=["organization", "status"], name="website_crm_organiz_0411f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmtask",
            index=models.Index(
                fields=["assigned_to", "due_date"],
                name="website_crm_assigne_bcf396_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmtask",
            index=models.Index(
                fields=["due_date"], name="website_crm_due_dat_c69427_idx"
            ),
        ),
    ]
