# Generated by Django 5.2.3 on 2025-07-26 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("website", "0036_crm_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True, help_text="Twitter handle without @", max_length=100
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        blank=True,
                        help_text="Instagram handle without @",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "CRM Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="crmcompany",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcompany",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcompany",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_companies",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcompany",
            index=models.Index(
                fields=["organization", "name"], name="website_crm_organiz_a4c63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmcompany",
            index=models.Index(
                fields=["assigned_to", "-created_at"],
                name="website_crm_assigne_aecab6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcompany",
            index=models.Index(fields=["email"], name="website_crm_email_f58287_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="crmcompany",
            unique_together={("organization", "name")},
        ),
    ]
