# Generated by Django 5.2.3 on 2025-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0037_add_crm_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaTester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("invited_to_testflight", models.BooleanField(default=False)),
                (
                    "testflight_invitation_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser/device info"),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True, help_text="How they found us", max_length=100
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="betatester",
            index=models.Index(fields=["email"], name="website_bet_email_a610eb_idx"),
        ),
        migrations.AddIndex(
            model_name="betatester",
            index=models.Index(
                fields=["invited_to_testflight"], name="website_bet_invited_f5b313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="betatester",
            index=models.Index(
                fields=["created_at"], name="website_bet_created_7ededc_idx"
            ),
        ),
    ]
