# Generated by Django 5.2.3 on 2025-07-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0038_betatester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmcompany",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn company page URL"),
        ),
    ]
