# Generated by Django 5.2.3 on 2025-07-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0039_remove_pageview_website_pag_session_61c15b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandtweet",
            name="bookmark_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of bookmarks of this tweet (only for own tweets)",
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="like_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of likes on this tweet"
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="metrics_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time metrics were fetched from Twitter",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="quote_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of quote tweets of this tweet"
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="reply_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of replies to this tweet"
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="retweet_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of retweets of this tweet"
            ),
        ),
    ]
