# Generated by Django 5.2.3 on 2025-07-27 21:55

from django.db import migrations, models


def populate_tweet_strategies(apps, schema_editor):
    """Populate the database with predefined tweet strategies"""
    TweetStrategy = apps.get_model("website", "TweetStrategy")

    strategies = [
        {
            "name": "Breaking News & Trends",
            "category": "news_trend",
            "description": "React to current events and trending topics in your industry",
            "prompt_template": "Write a tweet about the latest news or trend related to {brand_name}. Make it timely and relevant. Include your perspective or how it affects your audience.",
            "example_output": "The latest AI developments are reshaping how we work! At {brand_name}, we're excited about the possibilities this brings to our industry. What trends are you watching? #AI #Innovation",
            "tone_suggestions": ["informative", "excited", "professional"],
            "hashtag_suggestions": ["#trending", "#news", "#industry", "#innovation"],
            "timing_suggestions": {
                "best_times": ["9AM", "1PM", "5PM"],
                "frequency": "as_needed",
            },
        },
        {
            "name": "Product Feature Spotlight",
            "category": "product_feature",
            "description": "Highlight specific features or benefits of your product/service",
            "prompt_template": "Create a tweet that showcases a specific feature or benefit of {brand_name}. Focus on how it solves a problem or adds value for customers.",
            "example_output": "🚀 New feature alert! Our latest update makes collaboration 50% faster. Teams can now sync in real-time across all devices. Try it today! #{brand_name} #productivity",
            "tone_suggestions": ["excited", "informative", "professional"],
            "hashtag_suggestions": [
                "#newfeature",
                "#productivity",
                "#innovation",
                "#update",
            ],
            "timing_suggestions": {
                "best_times": ["10AM", "2PM"],
                "frequency": "weekly",
            },
        },
        {
            "name": "Brand Values & Mission",
            "category": "brand_values",
            "description": "Share your company's values, mission, and what you stand for",
            "prompt_template": "Write a tweet that reflects {brand_name}'s core values and mission. Make it authentic and show what drives your company.",
            "example_output": 'At {brand_name}, we believe technology should make life simpler, not more complicated. Every feature we build starts with one question: "Will this truly help our users?" #values #purpose',
            "tone_suggestions": ["authentic", "inspiring", "professional"],
            "hashtag_suggestions": ["#values", "#mission", "#purpose", "#culture"],
            "timing_suggestions": {"best_times": ["9AM", "3PM"], "frequency": "weekly"},
        },
        {
            "name": "Engagement & Questions",
            "category": "engagement",
            "description": "Ask questions and encourage interaction with your audience",
            "prompt_template": "Create an engaging tweet that asks your audience a question related to {brand_name}'s industry. Make it thought-provoking and encourage responses.",
            "example_output": "Quick question for our community: What's the biggest challenge you face when managing your team remotely? We're always looking for ways to improve! 💭 #{brand_name}",
            "tone_suggestions": ["conversational", "curious", "friendly"],
            "hashtag_suggestions": [
                "#question",
                "#community",
                "#feedback",
                "#discussion",
            ],
            "timing_suggestions": {
                "best_times": ["12PM", "4PM", "7PM"],
                "frequency": "2-3 times per week",
            },
        },
        {
            "name": "Educational Tips",
            "category": "educational",
            "description": "Share helpful tips, tutorials, or educational content",
            "prompt_template": "Share a valuable tip or piece of advice related to {brand_name}'s industry. Make it actionable and helpful for your audience.",
            "example_output": '💡 Pro tip: Before your next team meeting, try the "5-minute rule" - spend 5 minutes defining the desired outcome. It can save hours of circular discussion! #teamwork #productivity',
            "tone_suggestions": ["helpful", "informative", "friendly"],
            "hashtag_suggestions": ["#tip", "#productivity", "#advice", "#howto"],
            "timing_suggestions": {
                "best_times": ["10AM", "2PM"],
                "frequency": "2-3 times per week",
            },
        },
        {
            "name": "Promotional Content",
            "category": "promotional",
            "description": "Promote your products, services, or special offers",
            "prompt_template": "Create a promotional tweet for {brand_name} that highlights a special offer, new product, or key benefit. Keep it compelling but not overly salesy.",
            "example_output": "🎉 Limited time: Get 30% off your first 3 months with {brand_name}! Join thousands of teams already boosting their productivity. Link in bio! #sale #productivity",
            "tone_suggestions": ["exciting", "urgent", "professional"],
            "hashtag_suggestions": ["#sale", "#offer", "#limited", "#deal"],
            "timing_suggestions": {
                "best_times": ["11AM", "3PM"],
                "frequency": "sparingly",
            },
        },
        {
            "name": "Community Building",
            "category": "community",
            "description": "Build and engage with your community of followers",
            "prompt_template": "Write a tweet that celebrates your community or encourages community interaction around {brand_name}. Make it inclusive and appreciative.",
            "example_output": "Shoutout to our amazing community! 🙌 Your feedback helped us ship 12 new features this quarter. Keep the ideas coming - we're listening! #{brand_name}community",
            "tone_suggestions": ["appreciative", "inclusive", "warm"],
            "hashtag_suggestions": [
                "#community",
                "#thankyou",
                "#feedback",
                "#together",
            ],
            "timing_suggestions": {
                "best_times": ["12PM", "6PM"],
                "frequency": "weekly",
            },
        },
        {
            "name": "Behind the Scenes",
            "category": "behind_scenes",
            "description": "Show the human side of your business with behind-the-scenes content",
            "prompt_template": "Share something behind-the-scenes at {brand_name}. Could be team culture, workspace, process, or personal story. Make it authentic and relatable.",
            "example_output": "Coffee count at {brand_name} HQ today: 47 cups ☕ Our dev team is pushing hard on the new release. The energy is incredible! #behindthescenes #teamwork",
            "tone_suggestions": ["casual", "authentic", "personal"],
            "hashtag_suggestions": [
                "#behindthescenes",
                "#teamlife",
                "#culture",
                "#authentic",
            ],
            "timing_suggestions": {"best_times": ["2PM", "5PM"], "frequency": "weekly"},
        },
        {
            "name": "User Generated Content",
            "category": "user_generated",
            "description": "Share and celebrate content created by your users or customers",
            "prompt_template": "Create a tweet that celebrates or shares user-generated content related to {brand_name}. Show appreciation for your customers and their creativity.",
            "example_output": 'Love seeing how @username uses {brand_name} to organize their startup! 🚀 "It\'s like having a personal assistant for my entire business" - exactly what we hoped to achieve! #customer',
            "tone_suggestions": ["appreciative", "proud", "celebratory"],
            "hashtag_suggestions": [
                "#customer",
                "#usergenerated",
                "#success",
                "#testimonial",
            ],
            "timing_suggestions": {
                "best_times": ["11AM", "4PM"],
                "frequency": "when available",
            },
        },
        {
            "name": "Industry Insights",
            "category": "industry_insight",
            "description": "Share insights and perspectives about your industry",
            "prompt_template": "Share an insightful perspective about trends or developments in {brand_name}'s industry. Position your brand as a thought leader.",
            "example_output": "The future of work isn't just remote - it's async. Companies that master asynchronous collaboration will have a massive advantage in attracting global talent. #{brand_name} #future",
            "tone_suggestions": ["thoughtful", "authoritative", "forward-thinking"],
            "hashtag_suggestions": ["#insights", "#industry", "#future", "#trends"],
            "timing_suggestions": {"best_times": ["9AM", "1PM"], "frequency": "weekly"},
        },
        {
            "name": "Seasonal & Timely",
            "category": "seasonal",
            "description": "Create content around holidays, seasons, or timely events",
            "prompt_template": "Create a seasonal or timely tweet that connects a current holiday, season, or event with {brand_name}. Make it relevant and engaging.",
            "example_output": "New year, new goals! 🎯 Whether you're planning to scale your team or streamline your workflow, {brand_name} is here to help make 2024 your most productive year yet! #newyear",
            "tone_suggestions": ["celebratory", "motivational", "timely"],
            "hashtag_suggestions": ["#seasonal", "#holiday", "#newyear", "#goals"],
            "timing_suggestions": {
                "best_times": ["varies by event"],
                "frequency": "seasonal",
            },
        },
        {
            "name": "Storytelling",
            "category": "storytelling",
            "description": "Tell compelling stories about your brand, customers, or journey",
            "prompt_template": "Tell a brief story related to {brand_name} - could be about your founding, a customer success, or a challenge you overcame. Make it engaging and relatable.",
            "example_output": '2 years ago, our founder was managing spreadsheets at 2AM for the 3rd night straight. "There has to be a better way," she thought. That frustration became {brand_name}. Sometimes the best solutions come from our biggest problems. 💡',
            "tone_suggestions": ["narrative", "inspiring", "personal"],
            "hashtag_suggestions": ["#story", "#journey", "#inspiration", "#startup"],
            "timing_suggestions": {
                "best_times": ["1PM", "7PM"],
                "frequency": "monthly",
            },
        },
    ]

    for strategy_data in strategies:
        TweetStrategy.objects.create(**strategy_data)


def reverse_populate_tweet_strategies(apps, schema_editor):
    """Remove all tweet strategies"""
    TweetStrategy = apps.get_model("website", "TweetStrategy")
    TweetStrategy.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0040_add_tweet_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tweet strategy", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news_trend", "News & Trends"),
                            ("product_feature", "Product Features"),
                            ("brand_values", "Brand Values"),
                            ("engagement", "Engagement"),
                            ("educational", "Educational"),
                            ("promotional", "Promotional"),
                            ("community", "Community Building"),
                            ("behind_scenes", "Behind the Scenes"),
                            ("user_generated", "User Generated Content"),
                            ("industry_insight", "Industry Insights"),
                            ("seasonal", "Seasonal/Timely"),
                            ("storytelling", "Storytelling"),
                        ],
                        help_text="Category of the tweet strategy",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this strategy accomplishes"
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="AI prompt template for generating tweets using this strategy. Use placeholders like {brand_name}, {brand_values}, {topic}, {competitor}, etc."
                    ),
                ),
                (
                    "example_output",
                    models.TextField(
                        blank=True,
                        help_text="Example of what a tweet generated with this strategy might look like",
                    ),
                ),
                (
                    "tone_suggestions",
                    models.JSONField(
                        default=list,
                        help_text="Suggested tones for this strategy (e.g., professional, casual, humorous)",
                    ),
                ),
                (
                    "hashtag_suggestions",
                    models.JSONField(
                        default=list, help_text="Suggested hashtags for this strategy"
                    ),
                ),
                (
                    "timing_suggestions",
                    models.JSONField(
                        default=dict,
                        help_text="Suggested timing for this strategy (best times, frequency, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this strategy is available for use",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this strategy has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tweet Strategy",
                "verbose_name_plural": "Tweet Strategies",
                "ordering": ["category", "name"],
            },
        ),
        migrations.RunPython(
            populate_tweet_strategies,
            reverse_populate_tweet_strategies,
        ),
    ]
