# Generated by Django 5.2.3 on 2025-07-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0041_add_tweet_strategies"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandtweet",
            name="link_clicks",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of tracking link clicks"
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Tweet strategy used to generate this tweet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tweets",
                to="website.tweetstrategy",
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="tracking_link",
            field=models.URLField(
                blank=True, help_text="Unique tracking link for this tweet", null=True
            ),
        ),
        migrations.AddField(
            model_name="brandtweet",
            name="tracking_token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for tracking link clicks",
                max_length=32,
            ),
        ),
    ]
