# Generated by Django 5.2.3 on 2025-07-28 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("website", "0043_make_tracking_token_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwitterMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        help_text="Twitter handle without @ symbol", max_length=100
                    ),
                ),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("contact", "Contact"),
                            ("unlinked", "Unlinked"),
                        ],
                        default="unlinked",
                        max_length=20,
                    ),
                ),
                (
                    "times_mentioned",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this handle has been mentioned",
                    ),
                ),
                ("last_mentioned_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_mentioned_at"],
            },
        ),
        migrations.AddField(
            model_name="tweetmention",
            name="brand_tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="twitter_mentions",
                to="website.brandtweet",
            ),
        ),
        migrations.AddField(
            model_name="tweetmention",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="twittermention",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_twitter_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="twittermention",
            name="crm_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked CRM company if this is a company handle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="twitter_mentions",
                to="website.crmcompany",
            ),
        ),
        migrations.AddField(
            model_name="twittermention",
            name="crm_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked CRM contact if this is an individual handle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="twitter_mentions",
                to="website.crmcontact",
            ),
        ),
        migrations.AddField(
            model_name="twittermention",
            name="first_mentioned_in",
            field=models.ForeignKey(
                help_text="The tweet where this handle was first mentioned",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_handles",
                to="website.brandtweet",
            ),
        ),
        migrations.AddField(
            model_name="twittermention",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="twitter_mentions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="tweetmention",
            name="twitter_mention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_mentions",
                to="website.twittermention",
            ),
        ),
        migrations.AddIndex(
            model_name="twittermention",
            index=models.Index(
                fields=["organization", "mention_type"],
                name="website_twi_organiz_5ee4d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="twittermention",
            index=models.Index(
                fields=["twitter_handle"], name="website_twi_twitter_efbd3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twittermention",
            index=models.Index(
                fields=["last_mentioned_at"], name="website_twi_last_me_a77200_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="twittermention",
            unique_together={("organization", "twitter_handle")},
        ),
        migrations.AlterUniqueTogether(
            name="tweetmention",
            unique_together={("twitter_mention", "brand_tweet")},
        ),
    ]
