# Generated by Django 5.2.3 on 2025-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0044_add_twitter_mention_tracking_clean"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinstagrampost",
            name="is_video_post",
            field=models.BooleanField(
                default=False, help_text="Whether this is a video post"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video for the Instagram post",
                null=True,
                upload_to="brand_instagram_posts/videos/",
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_duration",
            field=models.FloatField(
                blank=True, help_text="Video duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_prompt",
            field=models.TextField(
                blank=True, help_text="AI prompt used to generate video content"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_quality",
            field=models.CharField(
                choices=[("low", "Low"), ("high", "High")],
                default="low",
                help_text="Quality setting for video generation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for the video",
                null=True,
                upload_to="brand_instagram_posts/video_thumbnails/",
            ),
        ),
    ]
