# Generated by Django 5.2.3 on 2025-08-01 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0046_remove_orphaned_pageview_session_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("memory_total", models.FloatField(help_text="Total memory in MB")),
                ("memory_used", models.FloatField(help_text="Used memory in MB")),
                (
                    "memory_available",
                    models.FloatField(help_text="Available memory in MB"),
                ),
                (
                    "memory_percent",
                    models.FloatField(help_text="Memory usage percentage"),
                ),
                ("cpu_percent", models.FloatField(help_text="CPU usage percentage")),
                ("cpu_count", models.IntegerField(help_text="Number of CPU cores")),
                ("disk_total", models.FloatField(help_text="Total disk space in GB")),
                ("disk_used", models.FloatField(help_text="Used disk space in GB")),
                ("disk_free", models.FloatField(help_text="Free disk space in GB")),
                ("disk_percent", models.FloatField(help_text="Disk usage percentage")),
                (
                    "user_count",
                    models.IntegerField(default=0, help_text="Total number of users"),
                ),
                (
                    "organization_count",
                    models.IntegerField(
                        default=0, help_text="Total number of organizations"
                    ),
                ),
                (
                    "brand_count",
                    models.IntegerField(default=0, help_text="Total number of brands"),
                ),
                (
                    "post_count",
                    models.IntegerField(
                        default=0, help_text="Total number of posts/tweets"
                    ),
                ),
                (
                    "active_sessions",
                    models.IntegerField(
                        default=0, help_text="Number of active user sessions"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Statistics",
                "verbose_name_plural": "System Statistics",
                "ordering": ["-timestamp"],
            },
        )
    ]
