# Generated by Django 5.2.3 on 2025-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0047_add_systemstats_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_generation_task_uuid",
            field=models.CharField(
                blank=True,
                help_text="UUID of the video generation task for async processing",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_generation_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="none",
                help_text="Status of video generation task",
                max_length=20,
            ),
        ),
    ]
