# Generated by Django 5.2.3 on 2025-08-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0048_add_video_generation_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinstagrampost",
            name="comment_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of comments on this Instagram post"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="impressions",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of times this post was seen"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="like_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of likes on this Instagram post"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="metrics_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time metrics were fetched from Instagram",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="reach",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of unique accounts that saw this post"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="saved_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this post was saved"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="share_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of shares of this Instagram post"
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_views",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of video views (for video posts only)"
            ),
        ),
        migrations.AddIndex(
            model_name="systemstats",
            index=models.Index(
                fields=["-timestamp"], name="website_sys_timesta_1378c1_idx"
            ),
        ),
    ]
