# Generated by Django 5.2.3 on 2025-08-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0049_add_instagram_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Mark this brand as the default for its organization",
            ),
        ),
    ]
