# Generated by Django 5.2.4 on 2025-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0049_add_instagram_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="Gemnar AI Services Pricing", max_length=255
                    ),
                ),
                (
                    "page_description",
                    models.TextField(
                        default="Transparent pricing for AI-powered marketing services. No hidden fees, pay as you go."
                    ),
                ),
                (
                    "default_markup_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("show_comparison", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pricing Page Configuration",
                "verbose_name_plural": "Pricing Page Configurations",
            },
        ),
        migrations.CreateModel(
            name="PricingScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("services_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("scraped_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Pricing Scraping Log",
                "verbose_name_plural": "Pricing Scraping Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RunwarePricingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255, unique=True)),
                ("service_description", models.TextField(blank=True)),
                (
                    "runware_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("runware_unit", models.CharField(blank=True, max_length=100)),
                (
                    "gemnar_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Runware Pricing Data",
                "verbose_name_plural": "Runware Pricing Data",
                "ordering": ["service_name"],
            },
        ),
        migrations.AddField(
            model_name="pricingpageconfig",
            name="featured_services",
            field=models.ManyToManyField(blank=True, to="website.runwarepricingdata"),
        ),
    ]
