# Generated by Django 5.2.3 on 2025-08-03 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0050_add_brand_is_default"),
        ("website", "0050_pricingpageconfig_pricingscrapinglog_and_more"),
    ]

    operations = []
