# Generated by Django 5.2.3 on 2025-08-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0051_merge_20250803_0102"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Package name (e.g., 'Starter Pack')", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what's included in this package",
                    ),
                ),
                (
                    "credits_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of credits included in this package",
                        max_digits=10,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in USD", max_digits=10
                    ),
                ),
                (
                    "price_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in INR (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stripe_price_id_usd",
                    models.CharField(
                        blank=True,
                        help_text="Stripe price ID for USD pricing",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_id_inr",
                    models.CharField(
                        blank=True,
                        help_text="Stripe price ID for INR pricing",
                        max_length=255,
                    ),
                ),
                (
                    "cashfree_product_id",
                    models.CharField(
                        blank=True, help_text="Cashfree product ID", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this package is available for purchase",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured packages are highlighted in the UI",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for displaying packages (lower numbers first)",
                    ),
                ),
                (
                    "bonus_credits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Extra bonus credits included (shown separately)",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credit Package",
                "verbose_name_plural": "Credit Packages",
                "ordering": ["sort_order", "price_usd"],
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="credits_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current AI credits balance for this brand",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("usage", "Credit Usage"),
                            ("refund", "Credit Refund"),
                            ("bonus", "Bonus Credits"),
                            ("adjustment", "Manual Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of credits (positive for additions, negative for deductions)",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the transaction"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credit balance after this transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe/Cashfree payment intent ID for purchases",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "service_used",
                    models.CharField(
                        blank=True,
                        help_text="AI service used (e.g., 'runware_image_generation')",
                        max_length=100,
                    ),
                ),
                (
                    "api_request_id",
                    models.CharField(
                        blank=True,
                        help_text="API request ID for usage tracking",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="website.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Transaction",
                "verbose_name_plural": "Credit Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["brand", "-created_at"],
                        name="website_cre_brand_i_1a95c3_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="website_cre_transac_1884d2_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="website_cre_created_cf7d88_idx"
                    ),
                ],
            },
        ),
    ]
