# Generated by Django 5.2.3 on 2025-08-03 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0050_pricingpageconfig_pricingscrapinglog_and_more"),
        ("website", "0052_task_model_enhancements"),
    ]

    operations = []
