# Generated by Django 5.2.3 on 2025-08-04 17:30

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Safely remove the index if it exists.

    Note: On SQLite we intentionally do nothing to avoid dropping the index.
    """
    index_name = "website_pag_session_61c15b_idx"
    vendor = getattr(schema_editor.connection, "vendor", "")

    # Never drop this index on SQLite
    if vendor == "sqlite":
        return

    # First try the portable IF EXISTS form
    try:
        schema_editor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
        return
    except Exception:
        # Fall back to manual existence check per backend
        pass

    # Fallback for engines that don't support IF EXISTS
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if vendor == "postgresql":
            # Use IF EXISTS again (Postgres supports it);
            # if not, just ignore errors
            try:
                cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
            except Exception:
                pass
        else:
            # Generic attempt; ignore if it fails
            try:
                cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
            except Exception:
                # Try without IF EXISTS and without quotes
                try:
                    cursor.execute(f"DROP INDEX {index_name}")
                except Exception:
                    pass


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - do nothing since we're just cleaning up"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0053_merge_20250803_2130"),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_remove_index,
        ),
    ]
