# Generated by Django 5.2.3 on 2025-08-04 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0050_remove_pageview_website_pag_session_61c15b_idx"),
        ("website", "0054_fix_pageview_index_issue"),
    ]

    operations = []
