# Generated by Django 5.2.3 on 2025-08-17 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0053_create_initial_credit_packages"),
        ("website", "0055_merge_20250804_1756"),
    ]

    operations = []
