# Generated by Django 5.2.3 on 2025-08-17 14:19

from django.db import migrations


class Migration(migrations.Migration):
    # Merge conflicting migration branches
    dependencies = [
        ("website", "0053_create_initial_credit_packages"),
        ("website", "0055_merge_20250804_1756"),
    ]

    operations = []
