# Generated by Django 5.2.3 on 2025-08-23 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0056_merge_20250817_1419"),
        ("website", "0056_merge_20250817_2009"),
    ]

    operations = []
