# Generated by Django 5.2.3 on 2025-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0057_merge_20250823_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="instagram_app_token",
            field=models.CharField(
                blank=True,
                help_text="Last generated app access token (client_credentials). Optional; may expire quickly and is not always required.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_business_id",
            field=models.CharField(
                blank=True,
                help_text="Meta Business ID associated with the Instagram/Facebook app integration",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_user_token",
            field=models.CharField(
                blank=True,
                help_text="Explicit user access token (mirrors long-lived user access token; stored separately for clarity).",
                max_length=500,
                null=True,
            ),
        ),
    ]
