# Generated by Django 5.2.3 on 2025-11-25 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0058_remove_pageview_website_pag_session_61c15b_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("viewport", models.JSONField(default=dict)),
                ("node_count", models.IntegerField(default=0)),
                ("tags", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("content_creation", "Content Creation"),
                            ("automation", "Automation"),
                            ("data_processing", "Data Processing"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "workspaces",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Can Edit"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "workspace_shares",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
                ("viewport", models.JSONField(blank=True, null=True)),
                ("is_official", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workspace_templates",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
                ("viewport", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "workspace_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="pageview",
            name="website_pag_session_61c15b_idx",
        ),
        migrations.AddField(
            model_name="workspace",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceshare",
            name="shared_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces_shared_by_me",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceshare",
            name="shared_with_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceshare",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="website.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workspacetemplate",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceversion",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="workspaceversion",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="website.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["user", "-created_at"], name="workspaces_user_id_201b7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["is_public"], name="workspaces_is_publ_c75087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["deleted_at"], name="workspaces_deleted_4d5a36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceshare",
            index=models.Index(
                fields=["workspace"], name="workspace_s_workspa_341901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceshare",
            index=models.Index(
                fields=["shared_with_user"], name="workspace_s_shared__954b93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceshare",
            unique_together={("workspace", "shared_with_user")},
        ),
        migrations.AddIndex(
            model_name="workspacetemplate",
            index=models.Index(
                fields=["category"], name="workspace_t_categor_0dcf90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetemplate",
            index=models.Index(
                fields=["is_official"], name="workspace_t_is_offi_834ebc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetemplate",
            index=models.Index(
                fields=["-usage_count"], name="workspace_t_usage_c_7c4fc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceversion",
            index=models.Index(
                fields=["workspace", "-created_at"],
                name="workspace_v_workspa_390abc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceversion",
            unique_together={("workspace", "version_number")},
        ),
    ]
