# Generated by Django 5.2.3 on 2025-11-25 22:37
# Simplified to only create FlowWorkspace model

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0059_workspace_workspaceshare_workspacetemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Workspace",
                "verbose_name_plural": "Flow Workspaces",
                "db_table": "website_flow_workspace",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="flowworkspace",
            index=models.Index(
                fields=["user", "-updated_at"], name="website_flo_user_id_658d97_idx"
            ),
        ),
    ]
