# Generated by Django 5.2.3 on 2025-11-27 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0061_cloudinary_storage_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudinaryupload",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded the file (null for anonymous uploads)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloudinary_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
