# Generated by Django 5.2.3 on 2025-11-29 11:29

import django.db.models.deletion
import uuid
import website.workspace_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0063_add_slug_to_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=website.workspace_models.workspace_media_path
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for videos",
                        null=True,
                        upload_to=website.workspace_models.workspace_media_path,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Workspace Media",
                "verbose_name_plural": "Workspace Media",
                "db_table": "website_workspace_media",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workspaceshare",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="workspaceversion",
            name="workspace",
        ),
        migrations.AlterUniqueTogether(
            name="workspaceshare",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workspaceshare",
            name="shared_by_user",
        ),
        migrations.RemoveField(
            model_name="workspaceshare",
            name="shared_with_user",
        ),
        migrations.RemoveField(
            model_name="workspacetemplate",
            name="created_by_user",
        ),
        migrations.AlterUniqueTogether(
            name="workspaceversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workspaceversion",
            name="created_by_user",
        ),
        migrations.RenameIndex(
            model_name="flowworkspace",
            new_name="website_flo_slug_095054_idx",
            old_name="website_flo_slug_idx",
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_oauth_state",
            field=models.CharField(
                blank=True,
                help_text="Temporary OAuth state token for Instagram authentication flow",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowworkspace",
            name="clone_count",
            field=models.IntegerField(
                default=0, help_text="Number of times workspace was cloned"
            ),
        ),
        migrations.AddField(
            model_name="flowworkspace",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description shown on published workspace",
            ),
        ),
        migrations.AddField(
            model_name="flowworkspace",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Whether workspace is publicly accessible"
            ),
        ),
        migrations.AddField(
            model_name="flowworkspace",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When workspace was published", null=True
            ),
        ),
        migrations.AddField(
            model_name="flowworkspace",
            name="view_count",
            field=models.IntegerField(
                default=0, help_text="Number of views for public workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="flowworkspace",
            index=models.Index(
                fields=["is_public", "-published_at"],
                name="website_flo_is_publ_c7a8a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flowworkspace",
            index=models.Index(
                fields=["is_public", "-view_count"],
                name="website_flo_is_publ_cc1f27_idx",
            ),
        ),
        migrations.AddField(
            model_name="workspacemedia",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="website.flowworkspace",
            ),
        ),
        migrations.DeleteModel(
            name="Workspace",
        ),
        migrations.DeleteModel(
            name="WorkspaceShare",
        ),
        migrations.DeleteModel(
            name="WorkspaceTemplate",
        ),
        migrations.DeleteModel(
            name="WorkspaceVersion",
        ),
    ]
