# Generated by Django 5.2.3 on 2025-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0064_workspacemedia_remove_workspace_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='instagram_oauth_state',
            field=models.CharField(
                blank=True,
                help_text='Temporary OAuth state token for Instagram authentication flow',
                max_length=100,
                null=True
            ),
        ),
    ]
