# Generated by Django 5.2.3 on 2025-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0065_add_instagram_oauth_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="instagram_connected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when Instagram account was connected",
                null=True,
            ),
        ),
    ]
