# Generated by Django 5.2.8 on 2025-12-01 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0066_add_instagram_connected_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tweet_id", models.CharField(blank=True, max_length=50)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=False)),
                ("prompt_used", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_tweets",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queued Tweet",
                "verbose_name_plural": "Queued Tweets",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="TwitterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("api_secret", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("access_token_secret", models.CharField(max_length=255)),
                ("bearer_token", models.CharField(blank=True, max_length=255)),
                ("twitter_username", models.CharField(blank=True, max_length=100)),
                ("twitter_user_id", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("verification_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_config",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter Configuration",
                "verbose_name_plural": "Twitter Configurations",
            },
        ),
        migrations.CreateModel(
            name="TwitterAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("tweets_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("daily_impressions", models.IntegerField(default=0)),
                ("daily_engagements", models.IntegerField(default=0)),
                ("daily_retweets", models.IntegerField(default=0)),
                ("daily_likes", models.IntegerField(default=0)),
                ("daily_replies", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_analytics",
                        to="website.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter Analytics",
                "verbose_name_plural": "Twitter Analytics",
                "ordering": ["-date"],
                "unique_together": {("brand", "date")},
            },
        ),
    ]
