# Generated by Django 5.2.8 on 2025-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0067_queuedtweet_twitterconfig_twitteranalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandinstagrampost",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL for the image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandinstagrampost",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL for the video",
                max_length=500,
                null=True,
            ),
        ),
    ]
