# Generated by Django 5.2.3 on 2025-12-03 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0068_brandinstagrampost_image_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queuedtweet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Queued Tweet",
                "verbose_name_plural": "Queued Tweets",
            },
        ),
        migrations.RemoveField(
            model_name="queuedtweet",
            name="ai_generated",
        ),
        migrations.RemoveField(
            model_name="queuedtweet",
            name="prompt_used",
        ),
        migrations.RemoveField(
            model_name="queuedtweet",
            name="scheduled_time",
        ),
        migrations.RemoveField(
            model_name="queuedtweet",
            name="tweet_id",
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedtweet",
            name="twitter_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="content",
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuedtweet",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("scheduled", "Scheduled"),
                    ("posted", "Posted"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="queuedtweet",
            table="website_queuedtweet",
        ),
    ]
