from django.urls import path
from . import organization_views
from . import crm_views
from . import api_credit_views
from website.views import (
    tweet_strategies_dashboard,
    generate_strategy_tweet_with_website,
    generate_contact_tweet,
    send_contact_tweet,
)
from website import api_views

urlpatterns = [
    path("", organization_views.organization_list, name="organization_list"),
    path("add/", organization_views.organization_create, name="organization_add"),
    path(
        "<int:organization_pk>/",
        organization_views.organization_detail,
        name="organization_detail",
    ),
    # Credits management
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/credits/",
        organization_views.organization_brand_credits,
        name="organization_brand_credits",
    ),
    path(
        "<int:organization_pk>/edit/",
        organization_views.organization_edit,
        name="organization_edit",
    ),
    path(
        "<int:organization_pk>/delete/",
        organization_views.organization_delete,
        name="organization_delete",
    ),
    path(
        "<int:organization_pk>/users/add/",
        organization_views.organization_user_add,
        name="organization_user_add",
    ),
    path(
        "<int:organization_pk>/users/<int:pk>/edit/",
        organization_views.organization_user_edit,
        name="organization_user_edit",
    ),
    path(
        "<int:organization_pk>/users/<int:pk>/delete/",
        organization_views.organization_user_delete,
        name="organization_user_delete",
    ),
    # Brand management URLs
    path(
        "<int:organization_pk>/brands/",
        organization_views.organization_brand_list,
        name="organization_brand_list",
    ),
    path(
        "<int:organization_pk>/brands/add/",
        organization_views.organization_brand_create,
        name="organization_brand_create",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/",
        organization_views.organization_brand_detail,
        name="organization_brand_detail",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/connect-twitter/",
        organization_views.organization_brand_connect_twitter,
        name="organization_brand_connect_twitter",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/test-tweet/",
        organization_views.organization_brand_test_tweet,
        name="organization_brand_test_tweet",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/connect-instagram/",
        organization_views.organization_brand_connect_instagram,
        name="organization_brand_connect_instagram",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/test-instagram-token/",
        organization_views.test_instagram_access_token,
        name="test_instagram_token",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/test-instagram-business-id/",
        organization_views.test_instagram_business_id,
        name="test_instagram_business_id",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/generate-instagram-app-token/",
        organization_views.generate_instagram_app_access_token,
        name="generate_instagram_app_token",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/validate-facebook-app-id/",
        organization_views.validate_facebook_app_id,
        name="validate_facebook_app_id",
    ),
    # Instagram OAuth (automatic re-auth / recovery)
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/oauth/start/",
        organization_views.instagram_oauth_start,
        name="instagram_oauth_start",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/oauth/callback/",
        organization_views.instagram_oauth_callback,
        name="instagram_oauth_callback",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/debug-token/",
        organization_views.debug_instagram_token,
        name="debug_instagram_token",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/test-instagram/",
        organization_views.organization_brand_test_instagram_post,
        name="organization_brand_test_instagram",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/update-field/<str:field_name>/",
        organization_views.update_instagram_field,
        name="update_instagram_field",
    ),
    # CRM URLs
    path(
        "<int:organization_pk>/crm/",
        crm_views.crm_dashboard,
        name="crm_dashboard",
    ),
    path(
        "<int:organization_pk>/crm/reports/",
        crm_views.crm_reports,
        name="crm_reports",
    ),
    # Contact Management
    path(
        "<int:organization_pk>/crm/contacts/",
        crm_views.contact_list,
        name="crm_contact_list",
    ),
    path(
        "<int:organization_pk>/crm/contacts/create/",
        crm_views.contact_create,
        name="crm_contact_create",
    ),
    path(
        "<int:organization_pk>/crm/contacts/<int:contact_pk>/",
        crm_views.contact_detail,
        name="crm_contact_detail",
    ),
    # Company Management
    path(
        "<int:organization_pk>/crm/companies/",
        crm_views.company_list,
        name="crm_company_list",
    ),
    path(
        "<int:organization_pk>/crm/companies/create/",
        crm_views.company_create,
        name="crm_company_create",
    ),
    path(
        "<int:organization_pk>/crm/companies/<int:company_pk>/",
        crm_views.company_detail,
        name="crm_company_detail",
    ),
    path(
        "<int:organization_pk>/crm/companies/<int:company_pk>/edit/",
        crm_views.company_edit,
        name="crm_company_edit",
    ),
    path(
        "<int:organization_pk>/crm/companies/<int:company_pk>/get-latest-tweet/",
        crm_views.get_latest_tweet,
        name="crm_get_latest_tweet",
    ),
    path(
        "<int:organization_pk>/crm/companies/<int:company_pk>/generate-contact-tweet/",
        generate_contact_tweet,
        name="crm_generate_contact_tweet",
    ),
    path(
        "<int:organization_pk>/crm/companies/<int:company_pk>/send-contact-tweet/",
        send_contact_tweet,
        name="crm_send_contact_tweet",
    ),
    # Twitter Mentions Tracking
    path(
        "<int:organization_pk>/crm/twitter-mentions/",
        crm_views.twitter_mentions_dashboard,
        name="crm_twitter_mentions",
    ),
    # Deal Management
    path(
        "<int:organization_pk>/crm/deals/",
        crm_views.deal_list,
        name="crm_deal_list",
    ),
    path(
        "<int:organization_pk>/crm/deals/create/",
        crm_views.deal_create,
        name="crm_deal_create",
    ),
    path(
        "<int:organization_pk>/crm/deals/<int:deal_pk>/",
        crm_views.deal_detail,
        name="crm_deal_detail",
    ),
    # Activity Management
    path(
        "<int:organization_pk>/crm/activities/",
        crm_views.activity_list,
        name="crm_activity_list",
    ),
    # Task Management
    path(
        "<int:organization_pk>/crm/tasks/",
        crm_views.task_list,
        name="crm_task_list",
    ),
    # AJAX endpoints
    path(
        "<int:organization_pk>/crm/contacts/<int:contact_pk>/add-note/",
        crm_views.quick_add_note,
        name="crm_quick_add_note",
    ),
    path(
        "<int:organization_pk>/crm/deals/<int:deal_pk>/update-stage/",
        crm_views.update_deal_stage,
        name="crm_update_deal_stage",
    ),
    # Invitation management URLs
    path(
        "<int:organization_pk>/invitations/",
        organization_views.organization_invitation_list,
        name="organization_invitation_list",
    ),
    path(
        "<int:organization_pk>/invitations/send/",
        organization_views.organization_invitation_send,
        name="organization_invitation_send",
    ),
    path(
        "<int:organization_pk>/invitations/<int:invitation_pk>/cancel/",
        organization_views.organization_invitation_cancel,
        name="organization_invitation_cancel",
    ),
    path(
        "<int:organization_pk>/invitations/<int:invitation_pk>/resend/",
        organization_views.organization_invitation_resend,
        name="organization_invitation_resend",
    ),
    # Public invitation acceptance URL (no organization_pk needed)
    path(
        "invitation/<uuid:token>/accept/",
        organization_views.organization_invitation_accept,
        name="organization_invitation_accept",
    ),
    # Brand social media queue management
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/",
        organization_views.brand_tweet_queue,
        name="brand_tweet_queue",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweet-strategies/",
        tweet_strategies_dashboard,
        name="tweet_strategies_dashboard",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/",
        organization_views.brand_instagram_queue,
        name="brand_instagram_queue",
    ),
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/instagram/<int:post_id>/delete/",
        organization_views.brand_instagram_post_delete,
        name="brand_instagram_post_delete",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/create/",
        organization_views.brand_tweet_create,
        name="brand_tweet_create",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/update/",
        organization_views.brand_tweet_update,
        name="brand_tweet_update",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/generate-ai-text/",
        organization_views.brand_tweet_generate_ai_text,
        name="brand_tweet_generate_ai_text",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/generate-ai-tweet-from-website/",
        organization_views.brand_tweet_generate_ai_from_website,
        name="brand_tweet_generate_ai_from_website",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/generate-ai-instagram-from-website/",
        organization_views.brand_instagram_generate_ai_from_website,
        name="brand_instagram_generate_ai_from_website",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/generate-image/",
        organization_views.brand_tweet_generate_image,
        name="brand_tweet_generate_image",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/post-now/",
        organization_views.brand_tweet_post_now,
        name="brand_tweet_post_now",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/delete/",
        organization_views.brand_tweet_delete,
        name="brand_tweet_delete",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/delete-from-twitter/",
        organization_views.brand_tweet_delete_from_twitter,
        name="brand_tweet_delete_from_twitter",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/update-schedule/",
        organization_views.brand_tweet_update_schedule,
        name="brand_tweet_update_schedule",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/schedule-next-slot/",
        organization_views.brand_tweet_schedule_next_slot,
        name="brand_tweet_schedule_next_slot",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/tweets/"
        "<int:tweet_id>/refresh-metrics/",
        organization_views.brand_tweet_refresh_metrics,
        name="brand_tweet_refresh_metrics",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/instagram-posts/"
        "<int:post_id>/refresh-metrics/",
        organization_views.brand_instagram_post_refresh_metrics,
        name="brand_instagram_post_refresh_metrics",
    ),
    # Brand export/import endpoints
    path(
        "<int:organization_pk>/brands/<int:brand_pk>/export/",
        organization_views.brand_export,
        name="brand_export",
    ),
    path(
        "<int:organization_pk>/brands/import/",
        organization_views.brand_import,
        name="brand_import",
    ),
    # API endpoints
    path(
        "api/ai/generate-image-openai/",
        api_views.generate_ai_image_openai,
        name="generate_ai_image_openai",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/generate-ai-video/",
        api_views.generate_ai_video,
        name="generate_ai_video",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/generate-instagram-video/",
        api_views.generate_instagram_video,
        name="generate_instagram_video",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/generate-strategy-tweet-with-website/",
        generate_strategy_tweet_with_website,
        name="generate_strategy_tweet_with_website",
    ),
    # Credit management API URLs
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/credits/info/",
        api_credit_views.brand_credit_info,
        name="brand_credit_info",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/credits/apply-coupon/",
        api_credit_views.apply_coupon,
        name="apply_coupon",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/credits/"
        "create-checkout-session/",
        organization_views.brand_credit_create_checkout_session,
        name="brand_credit_create_checkout_session",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/credits/test-usage/",
        api_credit_views.simulate_credit_usage,
        name="simulate_credit_usage",
    ),
    path(
        "organizations/<int:organization_pk>/brands/<int:brand_pk>/credits/add-test/",
        api_credit_views.add_test_credits,
        name="add_test_credits",
    ),
    path(
        "api/credits/packages/",
        api_credit_views.credit_packages,
        name="credit_packages",
    ),
]
