# Generated by Copilot on 2025-08-23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_room_chatconversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(
                upload_to="chat_images/",
                null=True,
                blank=True,
                help_text="Optional image attachment for this message",
            ),
        ),
    ]
